### ISSUE TITLE
TEB doesn't work with non-lethal obstacle?

### ISSUE THREAD

**Issue by marshalshi** [rst-tu-dortmund/teb_local_planner#106]
Thanks for making this nice project. And I am new for TEB. Sorry this just a question instead of issue.

Currently I'm using teb for local path planner with `static_layer` costmap, where existing lethal obstacle (cost >100) and non-lethal obstacle (cost < 100). And also, `static_layer` set `trinary_costmap` to `false`for both global planner and local planner such that all full spectrum of intermediate values are used.

When I tried to move cross `non-lethal` obstacle: the global path plan made a path which was round the `non-lethal` obstacle, but when movebase moving, TEB would cross the `non-lethal` obstacle (which just like the `non-lethal` obstacle didn't exist). 

I am not sure that: Does TEB have the ability to walk round the `non-lethal` obstacle according to cost map value (if existing lower cost sum path)?
 
![example](https://user-images.githubusercontent.com/1660070/48353964-8fcb1200-e6cb-11e8-9b5c-a5dc575fe28c.png)
The "red" area is non-lethal area which has <100 cost value. Blue line is global path. Red arrows are TEB path. 

Thanks for helping.

**Comment by croesmann** [comment]
Unfortunately, the concept of occupancy grids does not work well in combination with derivative-based optimization like in the teb_local_planner. Hence, I decided to only take lethal obstacles into account
(see [this](http://wiki.ros.org/teb_local_planner/Tutorials/Obstacle%20Avoidance%20and%20Robot%20Footprint%20Model) for more details).
However, I tried to achieve something like *inflation* by adding a separate cost function that is configured by the parameter `inflation_dist`, but it is still subject to *inflated* obstacles.

I am closing this for now, but feel free to answer if you have any ideas on how to improve/enhance the current implementation.
