### ISSUE TITLE
wheelbase param description and car-like robot model

### ISSUE THREAD

**Issue by beetleskin** [rst-tu-dortmund/teb_local_planner#11]
The wheelbase parameter name and description are somewhat misleading in my case: We have a car-like robot with steering axle in the front as well as the drive shaft (like a normal car). So steering and drive happen on the front axle. According to the description ..

> The distance between the drive shaft and steering axle. The value might be negative for back-wheeled robots (only required if ~<name>/cmd_angle_instead_rotvel is set to true). 

.. the value should be set to zero in our case, shouldn't it? However, the term _wheelbase_ means the discance between front and rear axle. So which one is meant here, or did I misunderstand the parameter description?

Also I'm not quite sure where you expect _/base_link_ to be with respect to the robot model (resp. the robot frame) and how it matters.
Related: http://answers.ros.org/question/237035/steering-axis-of-carlike-robot-with-teb_local_planner/

**Comment by croesmann** [comment]
See my answer [here](http://answers.ros.org/question/237035/steering-axis-of-carlike-robot-with-teb_local_planner/).

Indeed, the wheelbase definition was not correct. I have fixed it on the [wiki page](http://wiki.ros.org/teb_local_planner#Robot_Configuration_Parameters).

Thanks!

**Comment by beetleskin** [comment]
Thanks a lot for the detailed answer on answers.ros.org, that solves my problem and clears a lot of questions.
