### ISSUE TITLE
Oscillations around global path while using teb local planner - the same in simulation and the real robot

### ISSUE THREAD

**Issue by liwei0007** [rst-tu-dortmund/teb_local_planner#116]
I believe many people have the same problem with me when using teb,I use the diff drive robot ,the phenomenon in the real robot is worse than in simulation .However, the robot seems to oscillate around the global path. if the robot starts off to the right of the path, then goes to the left, tries to come back and again goes to the right.If anyone can solve it,please help me,thank you very much!

**Comment by liwei0007** [comment]
@croesmann

**Comment by croesmann** [comment]
closing this in favor of #92

**Comment by gsh89** [comment]
@liwei0007 Were you able to resolve this ?
