### ISSUE TITLE
teb_local_planner -> mavros -> ardurover

### ISSUE THREAD

**Issue by FPSychotic** [rst-tu-dortmund/teb_local_planner#122]
It is possible TEB send msg to MAVROS and this last commands to PIX4.
And a further question, can work TEB as local planner and SPBL or SPBL Lattice as global planner? The use the same topics etc?
Sorry if I asked something obvious put Im begginer,quite complicated this...XD

**Comment by croesmann** [comment]
Hi, please ask your question at answers.ros.org or first check the general compatibility of mavros and the navigation stack. The teb_local_planner is just a local planner plugin for the navigation stack.

You can use the SPBL lattice planner as global planner. However, most of the information of the global plan is possibly waived as the teb_local_planner takes the kinematic constraints by itself into account.
In most cases, you should be fine with the standard global planner.
