### ISSUE TITLE
err test node

### ISSUE THREAD

**Issue by xiaoyuanzh** [rst-tu-dortmund/teb_local_planner#123]
No robot footprint model specified for trajectory optimization. Using point-shaped model.
0x2c7f230 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x20d7fb0) ): Attempt to set a screen on a child window.
0x2c7f6b0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x20d7fb0) ): Attempt to set a screen on a child window.
0x2c7b020 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x20d7fb0) ): Attempt to set a screen on a child window.
0x2c7a4c0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x20d7fb0) ): Attempt to set a screen on a child window.
[rviz-3] process has died [pid 4901, exit code -11, cmd /opt/ros/kinetic/lib/rviz/rviz -d /home/a/zxy/catkin_ws/src/teb_local_planner-kinetic-devel/cfg/rviz_test_optim.rviz __name:=rviz __log:=/home/a/.ros/log/e5b15ba8-6037-11e9-8427-88b11143c0c4/rviz-3.log].
log file: /home/a/.ros/log/e5b15ba8-6037-11e9-8427-88b11143c0c4/rviz-3*.log

**Comment by croesmann** [comment]
Closing this since it is obviously related to #127. Please add a comment if I am wrong ;-)
