### ISSUE TITLE
Error during source code compilation

### ISSUE THREAD

**Issue by nature1949** [rst-tu-dortmund/teb_local_planner#136]
When I did the source compilation process, I get an error:
`
teb_local_planner_ros.cpp:229:40: error: no matching function for call to ‘costmap_2d::Costmap2DROS::getRobotPose(tf::Stamped<tf::Transform>&)’
   costmap_ros_->getRobotPose(robot_pose);
                                        ^

/opt/ros/kinetic/include/class_loader/meta_object.hpp:198:16: error: invalid new-expression of abstract class type ‘teb_local_planner::TebLocalPlannerROS’
     return new C;
                ^
`

What is the cause of the error? And what should I do?

**Comment by minghuizhou123** [comment]
me too, Have you solved it?

**Comment by minghuizhou123** [comment]
![Screenshot from 2019-06-04 11-15-34](https://user-images.githubusercontent.com/49223640/58848691-1bcd7700-86ba-11e9-8ee8-09d694cfb439.png)

**Comment by YujieLu** [comment]
Maybe you should check out the branch according to the distribution of your ros. For me, I checkout melodic-devel, then all problems solved.

**Comment by TanyuSir** [comment]
Did you solve this error? I have encountered the same problem.

**Comment by TanyuSir** [comment]
I have encountered the same problem.But I solved it by the following method.
in your catkin_ws
git clone https://github.com/rst-tu-dortmund/costmap_converter.git
then
catkin_make

**Comment by TanyuSir** [comment]
Did you solve this error? I have encountered the same problem.

**Comment by TanyuSir** [comment]
The above problem is solved by the following methods
https://answers.ros.org/question/329601/teb_local_planner-compilation-error/
