### ISSUE TITLE
TimedElasticBand: insertPose and insertTimeDiff not inline

### ISSUE THREAD

**Issue by neumann89** [rst-tu-dortmund/teb_local_planner#15]
Hi, 

while creating an extended version of the optimal planner which will add additional poses into the teb, I can not call teb_.insertPose because it is declared as inline in timed_elastic_band.cpp, although it is public in the header. The same problem is with the insertTimeDiff function.

Because of the inline there are no function symbols in the compiled library.

**Comment by croesmann** [comment]
Thanks for pointing this out. Fixed in  d3c743d.

**Comment by neumann89** [comment]
Thank you :+1:
