### ISSUE TITLE
Segfault when calling destructor without initializing

### ISSUE THREAD

**Issue by mtlazaro** [rst-tu-dortmund/teb_local_planner#158]
Hi all,
a simple program like this one:
```
int main(int argc, char **argv){
  TebOptimalPlanner teb;
}
```
produces a segfault. The reason is that in the destructor it tries to clear the graph without having been initialized. 

Suggested solution is to modify the destructor as:
```
TebOptimalPlanner::~TebOptimalPlanner()
{  
  if (optimizer_){
    clearGraph();
  }
}
```

Best,
Mayte.

**Comment by croesmann** [comment]
thanks for pointing this out @mtlazaro!
Fixed in kinetic and cherry-picked to melodic and dashing.
