### ISSUE TITLE
Determining the max translational and angular acceleration ?

### ISSUE THREAD

**Issue by gsh89** [rst-tu-dortmund/teb_local_planner#165]
If the max translational and angular acceleration are not available, what is a good way to obtain these values for a given robot?

**Comment by croesmann** [comment]
Hi, 
this question is better placed at answers.ros.org.
However, consider the following options:
- If you know your maximum motor/wheel acceleration you can compute them using simple kinematics, e.g. for a differential drive robot. You can find the equations in almost every robotics textbook.
- If you have a dynamic model of your robot, you can try to obtain them by simulation
- Perform some tests with your real robot: increase translational and rotational acceleration limits systematically and validate the actual motion.

**Comment by gsh89** [comment]
@croesmann Thank you for the pointers.
