### ISSUE TITLE
Where is the Reeds-shepp-path implement in the code?

### ISSUE THREAD

**Issue by Forichael** [rst-tu-dortmund/teb_local_planner#190]
I recently read teb_local_planner code and the author's paper, and author was mention about the Reeds-Shepp-Path in the paper 《Trajectory modification considering dynamic constraints of autonomous robots》, but I can not find any code about Reeds-Shepp-Path, may be I have missing some detail.

**Comment by croesmann** [comment]
Actually, there is no reeds-shepp path computation in the code. To my mind, the paper states that  reeds-shepp paths could be used for initialization. However, the ROS package here initializes a new trajectory using straight lines resp. the global plan which seems to work fine.
