### ISSUE TITLE
example carlike model in gazebo

### ISSUE THREAD

**Issue by glebos** [rst-tu-dortmund/teb_local_planner#20]
Hi,
do you have examples of a car-like gazebo model set up with teb local planner and an ackermann controller, which you could upload?

Thank you and kind regards.

**Comment by croesmann** [comment]
Hi @glebos,

unfortunately, I have no complete gazebo model that I can share at the moment.
For this kind of questions you might refer to [ROS Answers](http://answers.ros.org) in order to reach the whole community.

Cheers,
Christoph

**Comment by subodh-malgonde** [comment]
You can use the [MIT's Racecar Simulator](https://github.com/mit-racecar/racecar-simulator). It has a robot model with Ackermann (car like) steering.
