### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [rst-tu-dortmund/teb_local_planner#207]
Would you mind releasing this package also for the newest distribution ROS Noetic? :)

**Comment by croesmann** [comment]
Sure, I am waiting for move_base_flex to be released ([see here](https://github.com/magazino/move_base_flex/issues/193)). It is the only dependency that is missing in Noetic.

**Comment by doisyg** [comment]
That would be amazing to have teb release so soon in noetic. MBF compiles fine under Noetic so hopefully it won't be blocking too long

**Comment by croesmann** [comment]
done ;-)
