### ISSUE TITLE
boost::prior has moved. Compilation Failure for ROS2 Foxy on Ubuntu Focal 20.04LTS

### ISSUE THREAD

**Issue by 3wnbr1** [rst-tu-dortmund/teb_local_planner#214]
**Platform**
- OS : Ubuntu 20.04 LTS (arm64/amd64)
- ROS Version : Foxy (packages.ros.org)
- libboost : System version (1.71.x)

**Compiler error**
```
In file included from /home/runner/ros_ws/src/teb_local_planner/teb_local_planner/include/teb_local_planner/timed_elastic_band.h:633,
                 from /home/runner/ros_ws/src/teb_local_planner/teb_local_planner/src/timed_elastic_band.cpp:39:
/home/runner/ros_ws/src/teb_local_planner/teb_local_planner/include/teb_local_planner/timed_elastic_band.hpp: In member function ‘bool teb_local_planner::TimedElasticBand::initTrajectoryToGoal(BidirIter, BidirIter, Fun, double, double, boost::optional<double>, boost::optional<double>, boost::optional<double>, boost::optional<double>, int, bool)’:
/home/runner/ros_ws/src/teb_local_planner/teb_local_planner/include/teb_local_planner/timed_elastic_band.hpp:50:59: error: ‘prior’ is not a member of ‘boost’
   50 |     Eigen::Vector2d goal_position = fun_position( *boost::prior(path_end) );
      |                                                           ^~~~~
make[2]: *** [CMakeFiles/teb_local_planner.dir/build.make:93: CMakeFiles/teb_local_planner.dir/src/optimal_planner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/teb_local_planner.dir/all] Error 2
make: *** [Makefile:158: all] Error 2
```

**Description**
`boost::prior` and `boost::next` used to be defined in header `boost/utility.hpp` but for some reason, it as been moved to `boost/next_prior.hpp` since v1.67.x. Therefore, including `boost/utility.hpp` is no longer sufficient to use `boost::prior`

Conditional include will enforce backward compatibility and fix the issue
```cpp
#include <boost/utility.hpp>
#if BOOST_VERSION >= 106700
#include <boost/next_prior.hpp>
#endif
```

**Fix**
I fixed this for my team with this commit https://github.com/robotique-ecam/teb_local_planner/commit/be6749b8b5cc7b193841ca96cd2228ece2a0e771

**Comment by croesmann** [comment]
Thank you for pointing this out! I have replaced `boost::next` and `boost::prior` with its STL alternatives in 8bd805e29ef629a003880e22d67d9529da76a87d, as I progressively want to get rid of boost in ros2 anyway.
