### ISSUE TITLE
[ROS2] Sync ROS2 branch with PRs for ROS1 

### ISSUE THREAD

**Issue by SteveMacenski** [rst-tu-dortmund/teb_local_planner#240]
Analog to https://github.com/rst-tu-dortmund/teb_local_planner/pull/235 where we need to keep ROS2 up to date with these changes too - since ROS1 will be soon completely deprecated and ROS2 will be all what's left.

**Comment by SteveMacenski** [comment]
Especially the loop fix and any substantive bug / performance boosts (like #234 when merged)

**Comment by eliasdc** [comment]
Can we expect a sync? I think a lot of features are really necessary in the Foxy version. #231 is one of those features we really need.

**Comment by SteveMacenski** [comment]
@eliasdc PRs are appreciated

**Comment by SteveMacenski** [comment]
https://github.com/rst-tu-dortmund/teb_local_planner/pull/198 another PR to forward port to ros2-master

**Comment by SteveMacenski** [comment]
https://github.com/rst-tu-dortmund/teb_local_planner/issues/283 supersedes
