### ISSUE TITLE
use teb local planner in non 2D Map ? 

### ISSUE THREAD

**Issue by jediofgever** [rst-tu-dortmund/teb_local_planner#269]
Hi @croesmann ,
I am interested to know what architectural changes would be required to make `teb_local_planner` to control a robot with a non 2D occupancy grid(costmap) ? 
I highly appreciate your feedback on this.

**Comment by jcmonteiro** [comment]
Does the robot move in 2D space?

**Comment by jediofgever** [comment]
The robot moves in 3D space. However controlled states are still 3(x,y,yaw)
it is more related to environment representation, and avoiding obstacles in this representation.

**Comment by jcmonteiro** [comment]
Why not cast your 3D data onto 2D?

**Comment by jediofgever** [comment]
That’s the initial option but with casting 2D I will not be able to represent elevation , ramps,  bumps that aren’t necessarily obstacle

**Comment by torgeros** [comment]
> 
> 
> Why not cast your 3D data onto 2D?

The problem is that odometry in relation to the map is not reliable if the floor is not plain (moving distance is not equal to distance on map)

**Comment by jediofgever** [comment]
That will highly depend on the source of your odometry, some of visual/lidar based SLAM will provide accurate enough odometry in my opinion

**Comment by torgeros** [comment]
it is no longer odometry then but yeah.. but in our usecase for example we only have odometry for guessing our own position and that does indeed not work _that well_ on ramps...

**Comment by jediofgever** [comment]
do you have some other mechanism to perform absolute localization within a map or you just rely on odometery ? 
and do you mind directing me link of your project if its open sourced

**Comment by jcmonteiro** [comment]
I don't know your constraints, but I would say that if you are relying solely on odometry then you need to tackle that first. Then, you could most likely cast your data to 2D and you TEB as usual.

**Comment by torgeros** [comment]
this is not about me, we have a 2D map and tackeled our problems.
sadly we are participating in a competition, so our code is not open source
