### ISSUE TITLE
teb planner can not compute Velocity Commands in time

### ISSUE THREAD

**Issue by hapi007** [rst-tu-dortmund/teb_local_planner#27]
When i use teb_local_planner in kobuki , it can not  compute Velocity Commands to move_base node in time ,so move_base node print these info always and no other info:
[ WARN] [1476253731.838476254]: Control loop missed its desired rate of 3.0000Hz... the loop actually took 3.9523 seconds
[ WARN] [1476253994.264856069]: Map update loop missed its desired rate of 3.0000Hz... the loop actually took 12.3793 seconds

My params is default. When i used dwa, it is all right.
By the way, the cpu top info is fined ,there is 80% idle.

base_local_planner_params.yaml-------------
controller_frequency: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
base_local_planner: "teb_local_planner/TebLocalPlannerROS"
# base_local_planner: "dwa_local_planner/DWAPlannerROS"

TrajectoryPlannerROS:
   max_vel_x: 0.5
   min_vel_x: 0.1
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 1.0
   min_vel_theta: -1.0
   min_in_place_vel_theta: 0.4
   escape_vel: -0.1
   acc_lim_x: 1.5
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 1.2

   holonomic_robot: false
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.05  # 5 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.4
   gdist_scale: 0.8
   meter_scoring: true

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.05
   angular_sim_granularity: 0.1
   vx_samples: 8
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false
[teb_local_planner_params.txt](https://github.com/rst-tu-dortmund/teb_local_planner/files/523663/teb_local_planner_params.txt)

**Comment by alexbaucom17** [comment]
I had this same problem and turning enable_homotopy_class_planning to false fixed the issue for me. My suspicion is that move_base is not multi-threaded and so when teb_planner was taking up all the CPU on the same core as move_base it was causing problems. This would still make it look like there is lots of CPU left but that high idle is all from other cores. I could be wrong about that, but I would try turning off the homotopy planning and see if that works for you.

**Comment by chenxianbo** [comment]
i have the same problem, the param is default, when i set the new goal, someone of cpu cores goto 100%

**Comment by chenxianbo** [comment]
@hapi007 
maybe your obstacles is too many, I choose polygon costmap_converter,my 'costmap_converter_params.yaml' shows below
----------------------------------------------------------------------------------------------------------------------------------
TebLocalPlannerROS:
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  costmap_converter/CostmapToPolygonsDBSMCCH:
   cluster_max_distance: 0.5
   cluster_min_pts: 2
   cluster_max_pts: 10000
  convex_hull_min_pt_separation: 0.1
