### ISSUE TITLE
ros2-master build failed on Galactic

### ISSUE THREAD

**Issue by tal-grossman** [rst-tu-dortmund/teb_local_planner#308]
## Descrption
We just started examine the new galactic release. Build nav2 1.0.3 from src. 

## Issue
Failed to build teb ros2-master branch from src. 
build seem to fail on `optimal_planner.cpp`.
_snap shot of termnial output:_

![image](https://user-images.githubusercontent.com/54407092/120095701-fd2adb00-c12f-11eb-9f8b-36de5228c0f3.png)

**Comment by saadehmd** [comment]
The same error shows up for foxy-devel. The g2o build seems to be fine with all the dependencies met. Yet there's conflicts when building teb_planner. I have suspicion this has something to do with C++ version used to build both.
