### ISSUE TITLE
Build fails for foxy-devel/ros2-master/dashing-devel with g2o related incompatibilities

### ISSUE THREAD

**Issue by saadehmd** [rst-tu-dortmund/teb_local_planner#313]
**Tried building teb_local_planner in all 3 branches and it always ends up giving these errors in common:**

/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp: In static member function ‘static void teb_local_planner::TebOptimalPlanner::registerG2OTypes()’:
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:126:40: **error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::VertexPose>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&**’
  126 |   factory->registerType("VERTEX_POSE", new g2o::HyperGraphElementCreator<VertexPose>);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        |
      |                                        g2o::HyperGraphElementCreator<teb_local_planner::VertexPose>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:127:44: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::VertexTimeDiff>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  127 |   factory->registerType("VERTEX_TIMEDIFF", new g2o::HyperGraphElementCreator<VertexTimeDiff>);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            g2o::HyperGraphElementCreator<teb_local_planner::VertexTimeDiff>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:129:46: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeTimeOptimal>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  129 |   factory->registerType("EDGE_TIME_OPTIMAL", new g2o::HyperGraphElementCreator<EdgeTimeOptimal>);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              |
      |                                              g2o::HyperGraphElementCreator<teb_local_planner::EdgeTimeOptimal>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:130:47: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeShortestPath>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  130 |   factory->registerType("EDGE_SHORTEST_PATH", new g2o::HyperGraphElementCreator<EdgeShortestPath>);
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               g2o::HyperGraphElementCreator<teb_local_planner::EdgeShortestPath>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:131:42: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeVelocity>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  131 |   factory->registerType("EDGE_VELOCITY", new g2o::HyperGraphElementCreator<EdgeVelocity>);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          g2o::HyperGraphElementCreator<teb_local_planner::EdgeVelocity>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:132:52: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeVelocityHolonomic>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  132 |   factory->registerType("EDGE_VELOCITY_HOLONOMIC", new g2o::HyperGraphElementCreator<EdgeVelocityHolonomic>);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                    |
      |                                                    g2o::HyperGraphElementCreator<teb_local_planner::EdgeVelocityHolonomic>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:133:46: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeAcceleration>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  133 |   factory->registerType("EDGE_ACCELERATION", new g2o::HyperGraphElementCreator<EdgeAcceleration>);
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              |
      |                                              g2o::HyperGraphElementCreator<teb_local_planner::EdgeAcceleration>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:134:52: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationStart>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  134 |   factory->registerType("EDGE_ACCELERATION_START", new g2o::HyperGraphElementCreator<EdgeAccelerationStart>);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                    |
      |                                                    g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationStart>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:135:51: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationGoal>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  135 |   factory->registerType("EDGE_ACCELERATION_GOAL", new g2o::HyperGraphElementCreator<EdgeAccelerationGoal>);
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationGoal>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:136:56: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationHolonomic>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  136 |   factory->registerType("EDGE_ACCELERATION_HOLONOMIC", new g2o::HyperGraphElementCreator<EdgeAccelerationHolonomic>);
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                        |
      |                                                        g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationHolonomic>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:137:62: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationHolonomicStart>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  137 |   factory->registerType("EDGE_ACCELERATION_HOLONOMIC_START", new g2o::HyperGraphElementCreator<EdgeAccelerationHolonomicStart>);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              |
      |                                                              g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationHolonomicStart>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:138:61: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationHolonomicGoal>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  138 |   factory->registerType("EDGE_ACCELERATION_HOLONOMIC_GOAL", new g2o::HyperGraphElementCreator<EdgeAccelerationHolonomicGoal>);
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |
      |                                                             g2o::HyperGraphElementCreator<teb_local_planner::EdgeAccelerationHolonomicGoal>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:139:55: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeKinematicsDiffDrive>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  139 |   factory->registerType("EDGE_KINEMATICS_DIFF_DRIVE", new g2o::HyperGraphElementCreator<EdgeKinematicsDiffDrive>);
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       |
      |                                                       g2o::HyperGraphElementCreator<teb_local_planner::EdgeKinematicsDiffDrive>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:140:52: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeKinematicsCarlike>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  140 |   factory->registerType("EDGE_KINEMATICS_CARLIKE", new g2o::HyperGraphElementCreator<EdgeKinematicsCarlike>);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                    |
      |                                                    g2o::HyperGraphElementCreator<teb_local_planner::EdgeKinematicsCarlike>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:141:42: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeObstacle>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  141 |   factory->registerType("EDGE_OBSTACLE", new g2o::HyperGraphElementCreator<EdgeObstacle>);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          g2o::HyperGraphElementCreator<teb_local_planner::EdgeObstacle>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:142:51: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeInflatedObstacle>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  142 |   factory->registerType("EDGE_INFLATED_OBSTACLE", new g2o::HyperGraphElementCreator<EdgeInflatedObstacle>);
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   g2o::HyperGraphElementCreator<teb_local_planner::EdgeInflatedObstacle>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:143:50: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeDynamicObstacle>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  143 |   factory->registerType("EDGE_DYNAMIC_OBSTACLE", new g2o::HyperGraphElementCreator<EdgeDynamicObstacle>);
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  g2o::HyperGraphElementCreator<teb_local_planner::EdgeDynamicObstacle>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:144:43: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgeViaPoint>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  144 |   factory->registerType("EDGE_VIA_POINT", new g2o::HyperGraphElementCreator<EdgeViaPoint>);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           |
      |                                           g2o::HyperGraphElementCreator<teb_local_planner::EdgeViaPoint>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:145:47: error: cannot convert ‘g2o::HyperGraphElementCreator<teb_local_planner::EdgePreferRotDir>*’ to ‘const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&’
  145 |   factory->registerType("EDGE_PREFER_ROTDIR", new g2o::HyperGraphElementCreator<EdgePreferRotDir>);
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               g2o::HyperGraphElementCreator<teb_local_planner::EdgePreferRotDir>*
In file included from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/include/teb_local_planner/optimal_planner.h:56,
                 from /home/saad/navigation2_ws/src/navigation2/teb_local_planner/teb_local_planner/src/optimal_planner.cpp:42:
/usr/local/include/g2o/core/factory.h:63:78: note:   initializing argument 2 of ‘void g2o::Factory::registerType(const string&, const std::shared_ptr<g2o::AbstractHyperGraphElementCreator>&)’
   63 |                     const std::shared_ptr<AbstractHyperGraphElementCreator>& c);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
make[2]: *** [CMakeFiles/teb_local_planner.dir/build.make:63: CMakeFiles/teb_local_planner.dir/src/timed_elastic_band.cpp.o] Error 1
make[2]: *** [CMakeFiles/teb_local_planner.dir/build.make:102: CMakeFiles/teb_local_planner.dir/src/visualization.cpp.o] Error 1
make[2]: *** [CMakeFiles/teb_local_planner.dir/build.make:141: CMakeFiles/teb_local_planner.dir/src/homotopy_class_planner.cpp.o] Error 1
make[2]: *** [CMakeFiles/teb_local_planner.dir/build.make:76: CMakeFiles/teb_local_planner.dir/src/optimal_planner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/teb_local_planner.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by jamestkpoon** [comment]
I had the same problem. What fixed it for me was making this fn:

template < typename T>
void register_type(g2o::Factory* factory, const std::string name)
{
  std::unique_ptr<g2o::HyperGraphElementCreator<T>> ptr_(new g2o::HyperGraphElementCreator<T>());
  std::shared_ptr<g2o::HyperGraphElementCreator<T>> shared_(std::move(ptr_));

  factory->registerType(name, shared_);
}

and then e.g. factory->registerType("EDGE_PREFER_ROTDIR", new g2o::HyperGraphElementCreator<EdgePreferRotDir>); becomes register_type< EdgePreferRotDir>(factory, "EDGE_PREFER_ROTDIR");

**Comment by spok7** [comment]
> template < typename T> void register_type(g2o::Factory* factory, const std::string name) { std::unique_ptr<g2o::HyperGraphElementCreator> ptr_(new g2o::HyperGraphElementCreator()); std::shared_ptr<g2o::HyperGraphElementCreator> shared_(std::move(ptr_));
> 
> factory->registerType(name, shared_); }

I'm not a c++ guy, so it took me a few hours before realizing the \<T\> got formatted away because of markdown.
For fellow copy-pasters struggling on Melodic/Noetic, here's the corrected code:
```cpp
template <typename T>
void register_type(g2o::Factory* factory, const std::string name)
{
  std::unique_ptr<g2o::HyperGraphElementCreator<T>> ptr_(new g2o::HyperGraphElementCreator<T>());
  std::shared_ptr<g2o::HyperGraphElementCreator<T>> shared_(std::move(ptr_));

  factory->registerType(name, shared_);
}
```
...or better yet, [just look at the commit below the comment I'm quoting](https://github.com/Tractonomy/teb_local_planner/commit/318372bb7747ee03bac095245a69f405c5dfe018).
