### ISSUE TITLE
Costmap_converter_msgsConfig not found

### ISSUE THREAD

**Issue by j-corvo** [rst-tu-dortmund/teb_local_planner#319]
Hello,

I'm having some difficulties putting TEB plugin to work with ROS2 foxy. I cloned the repository to my workspace folder and when I try to compile it, it throughs an error saying that it cannot find costmap_converter_msgs. 

Can anyone explain to me how can I resolve this issue?

The screenshot of the error is below:

![teb](https://user-images.githubusercontent.com/52609366/132674244-334fbf6b-00b6-42da-9ffb-862aea981fc8.png)

Thanks a lot for your help!

**Comment by saaangooooo** [comment]
Hello @rythm07 
I have the same problem.
Could you please tell me how you solved the problem?

**Comment by ziyi-joe** [comment]
I solve this problem by downloading the https://github.com/rst-tu-dortmund/costmap_converter.git and compile with teb
![2021-10-13 15-09-02 的屏幕截图](https://user-images.githubusercontent.com/47048080/137084342-443c73d4-90cc-4571-9dc8-5c5dd54ea305.png)
