### ISSUE TITLE
Polygon footprint model is not detecting obstacle collision

### ISSUE THREAD

**Issue by siferati** [rst-tu-dortmund/teb_local_planner#331]
Robot collides with obstacles when using polygon footprint, but works fine for other footprint models.

You can see in the following video (line model) the robot correctly stops before collision: infeasible footprints show in red and there are WARN logs about trajectory infeasibility.

https://user-images.githubusercontent.com/15384781/143421514-a16c42ea-ed2b-4606-93d5-0ec67166e6aa.mp4

But in the following video (polygon model) the robot does not stop: there are no infeasible footprints in red, and WARN logs only appear after the robot has already collided with the obstacle.

https://user-images.githubusercontent.com/15384781/143421963-812fdc95-b7c3-4758-9944-c800e22f73cb.mp4

**Comment by corot** [comment]
I realized that this is an effect of setting inflation weight to 1.
Reducing it to 0.1 solved the problem
