### ISSUE TITLE
Can I use these version on ros2 galactic?

### ISSUE THREAD

**Issue by Lindsay284** [rst-tu-dortmund/teb_local_planner#343]
I don't find pakages in galactic version, which is really sad news for me. Can I build foxy version teb_local_planner or else in galactic ros2?

**Comment by antoszy** [comment]
Hi @Lindsay284 
Did you manage to build use the planner in galactic?

**Comment by eliasdc** [comment]
`ros2-master` branch works on galactic

**Comment by Lindsay284** [comment]
> Hi @Lindsay284 Did you manage to build use the planner in galactic?

yes~ I want to do that

**Comment by Lindsay284** [comment]
> 

thank you bro~  I'll have a try

**Comment by SteveMacenski** [comment]
There's a `galactic` branch now, but yes, historically `ros2-master` would have been the right answer.
