### ISSUE TITLE
saturateVelocity issue in ros2-master

### ISSUE THREAD

**Issue by stu00608** [rst-tu-dortmund/teb_local_planner#365]
Hello, I'm using ROS2 Galactic and running TEB controller in `ros2-master` branch ([6d782b](https://github.com/rst-tu-dortmund/teb_local_planner/commit/6d782bf1deb9c86a6ececeec066601e924006318))

The robot I'm using is a holonomic robot, I found the linear y velocity is over the limit a lot.
`max_vel_y` is 0.25.
![teb1](https://user-images.githubusercontent.com/40068587/166437612-17b23455-944a-4e2b-a7e8-cc0a888ea426.png)
 
So I checked the foxy branch. Apparantly, the issue is because the ratio calculation.
![Screenshot from 2022-05-03 17-10-53](https://user-images.githubusercontent.com/40068587/166437948-d84bca1b-1990-412e-8846-e7c6829c7776.png)

But it seems been solved in foxy branch. 
![teb2](https://user-images.githubusercontent.com/40068587/166437877-3a55ff0d-56ea-4e29-acc5-120a73df0ff9.png)

Then I'm not sure, should I keep develop in `ros2-master` branch? In this case, I can create a PR and fix that piece.
Also, will you guys release a galactic branch?

Thank you!

**Comment by stu00608** [comment]
I think the reason to calculate the ratio but not simply limit the velocity at maximum value is because the flag `use_proportional_saturation` , but I don't see this parameter in rqt_reconfigure, so is it deprecated?

**Comment by corot** [comment]
[This PR](https://github.com/rst-tu-dortmund/teb_local_planner/pull/324/files) solves the problem, right?

If so, I can open the same for all non-fixed branches

**Comment by stu00608** [comment]
@corot Yes, that solves the problem, not sure how many branches has this issue but at least in `ros2-master`.

**Comment by corot** [comment]
thanks PaRed to noetic and ROS2
- https://github.com/rst-tu-dortmund/teb_local_planner/pull/367
- https://github.com/rst-tu-dortmund/teb_local_planner/pull/368 

Thanks @kenomo for the fix, and @renan028 for the review

**Comment by stu00608** [comment]
Thanks!
