### ISSUE TITLE
polygon obstacles

### ISSUE THREAD

**Issue by Fancy-a-good-name** [rst-tu-dortmund/teb_local_planner#389]
After the algorithm is reproduced in ROS, I just replaced the pointobstacles with polygonobstacles. But the result is shown in the figure. I would like to ask what causes this.After debugging, it is found that g2o recorded this obstacle when creating edges.I don't know why this happens, so I'd like to ask you guys.
 thanks！！！

![image](https://user-images.githubusercontent.com/90506503/200227661-a69c57df-d8c5-4c8e-8488-b09c83594aef.png)

**Comment by jaykorea** [comment]
same issue here

**Comment by xhy1599** [comment]
have you solved the problem?

**Comment by jaykorea** [comment]
> have you solved the problem?

I just activate via sep points to avoid this issue
