### ISSUE TITLE
Tricycle drive problems with left turns

### ISSUE THREAD

**Issue by thanujadax** [rst-tu-dortmund/teb_local_planner#46]
I'm using teb_local_planner (which is by far the best local planner I've tried) on a robot with a tricycle drive. I have a set of global goals that sends the robot on a serpentine pattern. Although the left turns and right turns are perfectly symmetric in terms of the goals, the teb local planner generates a weird local path only for the left turns. Right turns are planned very smoothly.

Do you have any ideas what could be wrong? I'll be glad to submit a pull request if you could kindly give me some pointers

**Comment by croesmann** [comment]
I think this could be related to #71. I fixed a crucial bug introduced in Dec. 2016 (270d1daeaef069fc204978112e1ff08d7f698bb5) which was related to left/right turns.
I close this for now and if it is still present, please feel free to reopen :-)
