### ISSUE TITLE
adding extra penalties for switching between forward and reverse drive

### ISSUE THREAD

**Issue by yfzhang** [rst-tu-dortmund/teb_local_planner#48]
Hello,

I am trying to use teb_local_planner for an engine powered robot car. Sometimes the planner produces a plan consisting a lot of small trajectory segments which switch between forward and reverse drive repeatedly. However, the shifting motor in the robot car actually takes some time to change the gear between forward and reverse drive, which makes the frequent switching undesirable. Would it be possible to add extra cost for the drive direction switching? If possible, could you please advise which part of the code should I look into?

Thank you.

**Comment by croesmann** [comment]
Have you tried to adjust your acceleration limits, since the planner tries to find the minimum time trajectory.
Otherwise, it is not trivial to find a smooth and differentiable cost which penalizes motion traversals in general. Are you still facing this issue?
