### ISSUE TITLE
Remembering the object's position when navigating around the sampe area

### ISSUE THREAD

**Issue by ghost** [rst-tu-dortmund/teb_local_planner#56]
Hello again,

I tried to add and move around objects in the scene in order to observer the behaviour using Teb_planner ,it seems that the object's position and size when detection at the first try is remembered and taken into account in future tries. Is there a parameter that I can change so that each time the object detected is not used more than once only during run-time.

I read about it on one of the issues and @croesmann has mentioned he will push some changes regarding with it this summer.

Thanks in advance and cheers.

**Comment by croesmann** [comment]
hi @MomoTavas,
Do you mean objects in the [costmap_2d](http://wiki.ros.org/costmap_2d)? The costmap is not maintained by the teb_local_planner, so you need to update your navigation stack configuration. However, obstacles are usually cleared in case you receive new *valid* range sensor date or if you call the corresponding service call.

If you mean user-supplied obstacles provided via [ObstacleArrayMsg](http://docs.ros.org/kinetic/api/costmap_converter/html/msg/ObstacleArrayMsg.html), these are cleared at every stage, so you can clear all user-supplied (custom) obstacles by sending an empty obstacle list.

I hope this answers your question. If you are still unsure and if this question is still relevant, please comment and/or reopen this issue.
