### ISSUE TITLE
Using teb_local_planner's feedback_msg for control

### ISSUE THREAD

**Issue by ben-swain** [rst-tu-dortmund/teb_local_planner#62]
Are there any potential issues with using the trajectory points from teb_local_planner's /feedback_msg topic as the primary method of control? 

By this, I mean that there is a separate node which subscribes to the /feedback_msg topic, and based on the trajectory points, the node calculates a throttle, braking, and steering value to send to the vehicle controllers. /enable_homotopy_class_planning will probably be set to true.

**Comment by croesmann** [comment]
I don't see any reasons why the feedback msg should not be used for control.
The only thing to keep in mind is that you bypass the [move_base](http://wiki.ros.org/move_base) node and hence recovery behaviors cannot work. So you should better deactivate them in advance.
