### ISSUE TITLE
How to set via-points through code?

### ISSUE THREAD

**Issue by ben-swain** [rst-tu-dortmund/teb_local_planner#63]
How can I set via-points through code? The tutorial (http://wiki.ros.org/teb_local_planner/Tutorials/Following%20the%20Global%20Plan%20%28Via-Points%29) only shows how to set them in Rviz.

**Comment by croesmann** [comment]
Hi @ben-swain,

There is currently no public method/subscriber to set custom via-points to the local planner navigation plugin.
In case of `test_optim_node` you can send them to the same topic as Rviz is doing.

An implementation would be straightforward since via-points are already supported in the underlying planner code.
I'll see what I can do in the next days, otherwise, I would be happy for any pull request.

**Comment by croesmann** [comment]
It is now possible to add via-points via topics! I'll push a new release in a minute ;-)

**Comment by theudebart** [comment]
I see the changes on the kinetic-devel and also on tag 0.6.10, but when teb_local_planner is installed form the ros repositories at packages.ros.org there is no via_point topic.
When i run `apt list --installed | grep teb-local-planner` i get `ros-kinetic-teb-local-planner/xenial,now 0.6.10-0xenial-20180715-024256-0800 amd64 [installed]` so 0.6.10 is installed and with #74 there should be this option in 0.6.10. Is there any problem i oversee?

**Comment by croesmann** [comment]
I tried the same version from the repositories:
```
 ros-kinetic-teb-local-planner/xenial,now 0.6.10-0xenial-20180715-024256-0800 amd64 [installed]
```

The topic `/test_optim_node/via_points` is available in case of running the `test_optim_node`.
For a navigation setup, I invoked `roslaunch teb_local_planner_tutorials robot_diff_drive_in_stage.launch` and got topic `/move_base/TebLocalPlannerROS/via_points`.

Can you still confirm, that you don't have those topics available?

**Comment by theudebart** [comment]
Sorry for the late response.

If i start the `test_optim_node` there is a topic `/test_optim_node/via_points`. But should't there be also a topic `via_points` when i start a `move_base` node with param `base_local_planner` set to `teb_local_planner/TebLocalPlannerROS`?
