### ISSUE TITLE
How to set start and goal?

### ISSUE THREAD

**Issue by DanielArnett** [rst-tu-dortmund/teb_local_planner#66]
I can't find any documentation on how to set the start and goal poses? What topics do I need to set to change them in test_optim_node.launch? All I'm looking for is the name and format of the topics I need to set or parameters I need to change.

**Comment by xperroni** [comment]
As you can see [here](https://github.com/rst-tu-dortmund/teb_local_planner/blob/kinetic-devel/src/test_optim_node.cpp#L167), the start and goal poses are hard-coded, so unless you edit the source code and recompile the node, there's no way to change them.

**Comment by DanielArnett** [comment]
Thank you. If anyone wants to just edit this teb_local_planner default app
![image](https://user-images.githubusercontent.com/3029502/39390700-5489d6ec-4a66-11e8-8cb2-253132485e23.png)
[they can change the waypoints here](https://github.com/rst-tu-dortmund/teb_local_planner/blob/kinetic-devel/src/test_optim_node.cpp#L167). 

The better solution for me was to just use the [teb_local_planner_tutorials](https://github.com/rst-tu-dortmund/teb_local_planner_tutorials) and replace the simulated vehicle with my own robot.

Thank  you to everyone who's supported this amazing project.
