### ISSUE TITLE
Paper Citation

### ISSUE THREAD

**Issue by aarontan-git** [rst-tu-dortmund/teb_local_planner#75]
I know this isnt an issue regarding the repo; however, I would like to read this paper: **Trajectory modification considering dynamic constraints of autonomous robots** and understand the concept to cite it.

However it is not available online ...

Please help.

**Comment by croesmann** [comment]
Hi @aarontan94,

thank you for your interest in our research :-)

The paper is available at [ieeexplore](https://ieeexplore.ieee.org/document/6309484/).

You can try to contact me on [researchgate](https://www.researchgate.net/profile/Christoph_Roesmann).

Note, I also recommend a more recent article:

> C. Rösmann, F. Hoffmann and T. Bertram: Integrated online trajectory planning and optimization in distinctive topologies, Robotics and Autonomous Systems, Vol. 88, 2017, pp. 142–153.

Cheers,

Christoph
