### ISSUE TITLE
Combining with Arduino Servo Control

### ISSUE THREAD

**Issue by aarontan-git** [rst-tu-dortmund/teb_local_planner#79]
Hello,

I understand this is not really an issue, more so just a question.

I have successfully implemented the teb_local_planner for a differential drive system; however, I'd like to expand to a car like robot. From your tutorials, I know that this path planner is capable of planning for car like robots.

I am using this [package](http://wiki.ros.org/rosserial_arduino/Tutorials/Servo%20Controller) to control my steering servo motors, however I dont know how to combine the teb_local_planner with this servo control to start planning paths with move_base.

Can you please provide some suggestions on what I should do?

How do I send proper steering angles to the arduino to control the servos over ros?

Thank you,
Aaron

**Comment by croesmann** [comment]
Hi,

please do not cross-post. And as you said, this is not really an issue.
Answers are already provided at your [answers.ros.org question](https://answers.ros.org/question/295065/ackermann-steering-and-arduino-servo-control/).
