### ISSUE TITLE
Parameter global_plan_viapoint_sep  misspelling in teb_config.cpp ( line58 ) as global_plan_via_point_sep

### ISSUE THREAD

**Issue by winf** [rst-tu-dortmund/teb_local_planner#81]
this would cause reconfigure default value override yaml  Parameter setting values

**Comment by croesmann** [comment]
thanks a lot for pointing this out. Fixed in the kinetic-devel branch. I will also merge this into newer distros soon. For more details, check cb36d06.

Cheers,
Christoph
