### ISSUE TITLE
Straight global plans do not obey 'global_plan_viapoint_sep' nor 'max_global_plan_lookahead_dist' 

### ISSUE THREAD

**Issue by varandaas** [rst-tu-dortmund/teb_local_planner#82]
Hi all,

Whenever I send a straight global plan, TEB doesn't comply with these parameters and generates the whole trajectory to the goal (see the images below). 

The compliance with these parameters would be important if you want it to follow long trajectories, as TEB fails to compute local trajectories longer than ~75 meters (with my setup).

Good behavior with a curved trajectory (local costmap in white):
![good](https://user-images.githubusercontent.com/10373469/42096135-cd277602-7bb4-11e8-884a-40a1a3526a85.png)

Bad behavior with a straight trajectory (local costmap in white):
![bad](https://user-images.githubusercontent.com/10373469/42096134-ccfba1da-7bb4-11e8-87c0-9ab835c60744.png)

Is there any parameter/workaround to solve this?

If not, how easy would it be to fix it and create a parameter to solve this?

**Comment by croesmann** [comment]
Hi, 
that definitely looks like a bug. Can you please test my code from branch `global_plan_mod`. I did some changes there which might have an effect here.
Otherwise, I will check the code again.

Cheers,
Christoph

**Comment by varandaas** [comment]
Hello Christoph,

Thank you so much for your help! I've tested it on a couple examples and that branch solves the distance issue, given a straight trajectory. However, I noticed two behaviors that don't seem correct:

- It still doesn't respect the local costmap boundaries (screenshot below);
- I was also expecting it to follow that trajectory with viapoints like curved trajectories (and respecting the  'global_plan_viapoint_sep'), but couldn't make it.

![thankyou](https://user-images.githubusercontent.com/10373469/42099756-9d295056-7bbe-11e8-8b90-92360ef3d5d1.png)

Are you planning to merge this fix to the following releases? 

Can I help you further with testing?

Best,
Francisco

**Comment by croesmann** [comment]
I probably have another reason: how many points define your straight line? If it is just two, the behavior is reasonable. The local planner just iterates all points from the global plan until it is outside of the local costmap or the max dist is exceeded (this is similar to other local planners). In case of just two points the search will stop at the goal. 

You need to interpolate your straight line on a fine grained grid

**Comment by croesmann** [comment]
Yes I will merge that code and check your recent issues early next week

**Comment by varandaas** [comment]
You're right @croesmann, my straight line is 150 meters and my interpolation had only 20 points (7,5 meters between pts vs 8x8 meter local costmap and 3 meter 'max_global_plan_lookahead_dist'). Your explanation makes total sense, my mistake.

Thank you so much for the fixes :) Looking forward to the release.

**Comment by croesmann** [comment]
I pushed a new release to kinetic and lunar, but we need to wait until it gets synced ;-)
