### ISSUE TITLE
ROS Melodic 

### ISSUE THREAD

**Issue by AchmadFathoni** [rst-tu-dortmund/teb_local_planner#83]
Hi,  since there is still no official repository for melodic what is alternative for properly install teb_local_planner on melodic?

**Comment by croesmann** [comment]
Hi,
the navigation stack has not been released for melodic yet (see [here](https://github.com/ros-planning/navigation/issues/749)) and hence is still [blocking](http://repositories.ros.org/status_page/blocked_releases_melodic.html?q=teb&s=6&r=1) the teb_local_planner package. As soon as it is released, I'll release the teb_local_planner and costmap_converter.

Cheers,
Christoph

Edit: you can try to build navigation, the costmap_converter and the teb_local_planner from source. But I haven't tested it for melodic yet.

**Comment by boilerbots** [comment]
The tf2 changes to the costmap_2d being made for melodic need to be implemented, code no longer compiles.

**Comment by mintar** [comment]
Navigation has been released into melodic: https://github.com/ros/rosdistro/pull/18657

So there's nothing blocking a teb_local_planner release into Melodic now.

**Comment by croesmann** [comment]
thanks! I pushed a release yesterday with tf2 migration, still waiting for all build farm jobs to complete resp. some ARM builds failed due to an unknown compiler reason (maybe to less RAM?), so waiting for rebuild.

**Comment by AchmadFathoni** [comment]
@croesmann Thank you very much!
