### ISSUE TITLE
in the function "calculateHSignature" skip really close obstacles

### ISSUE THREAD

**Issue by chenxianbo** [rst-tu-dortmund/teb_local_planner#90]
void calculateHSignature(BidirIter path_start, BidirIter path_end, Fun fun_cplx_point, const ObstContainer* obstacles)
{
 .....
                //if (diff.real()!=0 || diff.imag()!=0)
                if (std::abs(diff)<0.05) // skip really close obstacles
                    Al /= diff;
                else
                    continue;
                }
 .....
}

when abs(diff)<0.05, we get it calculate Al, but the note say " skip really close obstacles", it is opposite

**Comment by croesmann** [comment]
thanks a lot, you're right. fixed in kinetic-devel. I will port this to other distributions as well.
